name: meeus
description: Dart implementations of algorithms from the book "Astronomical Algorithms, 2nd edition" by Jean Meeus.
version: 0.2.0
homepage: https://github.com/shawnlauzon/meeus

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  unit: ^1.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
